# On these streets, we test in production!

[default]
DISCORD_TOKEN = "TODO"

RSS_WEBHOOKS = [
    "https://discord.com/api/webhooks/your_webhook_here"
]

RSS_OBSERVED_CHANNELS = [
    1234567890, # This should be an int
]
